default:
  before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

cache:
  paths:
  - .cache

.build-linux: &build-linux
  stage: build
  script:
  - go build -ldflags "-linkmode external -extldflags -static" -o gomuks
  artifacts:
    paths:
    - gomuks

linux/amd64:
  <<: *build-linux
  image: dock.mau.dev/tulir/gomuks-build-docker:linux-amd64

linux/arm:
  <<: *build-linux
  image: dock.mau.dev/tulir/gomuks-build-docker:linux-arm

linux/arm64:
  <<: *build-linux
  image: dock.mau.dev/tulir/gomuks-build-docker:linux-arm64

windows/amd64:
  image: dock.mau.dev/tulir/gomuks-build-docker:windows-amd64
  stage: build
  script:
  - go build -ldflags "-linkmode external -extldflags -static" -o gomuks.exe
  artifacts:
    paths:
    - gomuks.exe
