image: debian:bullseye

build:
  stage: build
  cache:
    paths:
    - .cache
  before_script:
  - apt-get update
  - apt-get install -y git libolm-dev golang-go
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  script:
  - go build -o gomuks
  artifacts:
    paths:
    - gomuks
