build:
  stage: build
  image: golang:alpine
  cache:
    paths:
    - .cache
  before_script:
  - apk add --no-cache git build-base
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  script:
  - git clone https://gitlab.matrix.org/matrix-org/olm.git
  - cd olm
  - CFLAGS=-static-libgcc CPPFLAGS="-static-libgcc -static-libstdc++" make static
  - cp build/libolm.a /usr/lib/ && cp -a include/olm/ /usr/include/
  - cd ..
  - go build -ldflags "-linkmode external -extldflags -static" -o gomuks
  artifacts:
    paths:
    - gomuks
