stages:
- build
- package

default:
  before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

cache:
  paths:
  - .cache

.build-linux: &build-linux
  stage: build
  script:
  - go build -ldflags "-linkmode external -extldflags -static" -o gomuks
  artifacts:
    paths:
    - gomuks

linux/amd64:
  <<: *build-linux
  image: dock.mau.dev/tulir/gomuks-build-docker:linux-amd64

linux/arm:
  <<: *build-linux
  image: dock.mau.dev/tulir/gomuks-build-docker:linux-arm

linux/arm64:
  <<: *build-linux
  image: dock.mau.dev/tulir/gomuks-build-docker:linux-arm64

windows/amd64:
  image: dock.mau.dev/tulir/gomuks-build-docker:windows-amd64
  stage: build
  script:
  - go build -ldflags "-linkmode external -extldflags -static" -o gomuks.exe
  artifacts:
    paths:
    - gomuks.exe

debian:
  image: debian
  stage: package
  dependencies:
  - linux/amd64
  only:
  - tags
  script:
  - mkdir -p deb/usr/bin
  - cp gomuks deb/usr/bin/gomuks
  - chmod -R -s deb/DEBIAN && chmod -R 0755 deb/DEBIAN
  - dpkg-deb --build deb gomuks.deb
  artifacts:
    paths:
    - gomuks.deb
